
/* Drop Tables */

DROP TABLE INTERS CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_COMMENT_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_COMMENT_LIKE CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_MEDIA CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD_TAG CASCADE CONSTRAINTS;
DROP TABLE MAINBOARD CASCADE CONSTRAINTS;
DROP TABLE RELATION CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_ALERT CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_MAP CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_MEDIA CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_PUSH CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE USERTABLE CASCADE CONSTRAINTS;
DROP TABLE AUTH CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_STATUS CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_AUTH_AUTH_PID;
DROP SEQUENCE SEQ_INTERS_INTERS_PID;
DROP SEQUENCE SEQ_MAINBOARD_COMMENT_COMMENT_MAINBOARD_COMMENT_COMMENT_PID;
DROP SEQUENCE SEQ_MAINBOARD_COMMENT_LIKE_MAINBOARD_COMMENT_LIKE_PID;
DROP SEQUENCE SEQ_MAINBOARD_COMMENT_MAINBOARD_COMMENT_PID;
DROP SEQUENCE SEQ_MAINBOARD_LIKE_MAINBOARD_LIKE_PID;
DROP SEQUENCE SEQ_MAINBOARD_MAINBOARD_PID;
DROP SEQUENCE SEQ_MAINBOARD_MEDIA_MAINBOARD_MEDIA_PID;
DROP SEQUENCE SEQ_MAINBOARD_TAG_MAINBOARD_TAG_PID;
DROP SEQUENCE SEQ_RELATION_RELATION_PID;
DROP SEQUENCE SEQ_SCHEDULE_ALERT_SCHEDULE_ALERT_PID;
DROP SEQUENCE SEQ_SCHEDULE_MAP_SCHEDULE_MAP_PID;
DROP SEQUENCE SEQ_SCHEDULE_MEDIA_SCHEDULE_MEDIA_PID;
DROP SEQUENCE SEQ_SCHEDULE_PUSH_SCHEDULE_PUSH_PID;
DROP SEQUENCE SEQ_SCHEDULE_SCHEDULE_PID;
DROP SEQUENCE SEQ_SCHEDULE_STATUS_SCHEDULE_STATUS_PID;
DROP SEQUENCE SEQ_USERTABLE_USER_PID;




/* Create Sequences */

CREATE SEQUENCE SEQ_AUTH_AUTH_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_INTERS_INTERS_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_COMMENT_COMMENT_MAINBOARD_COMMENT_COMMENT_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_COMMENT_LIKE_MAINBOARD_COMMENT_LIKE_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_COMMENT_MAINBOARD_COMMENT_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_LIKE_MAINBOARD_LIKE_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_MAINBOARD_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_MEDIA_MAINBOARD_MEDIA_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MAINBOARD_TAG_MAINBOARD_TAG_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_RELATION_RELATION_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_ALERT_SCHEDULE_ALERT_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_MAP_SCHEDULE_MAP_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_MEDIA_SCHEDULE_MEDIA_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_PUSH_SCHEDULE_PUSH_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_SCHEDULE_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE_STATUS_SCHEDULE_STATUS_PID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_USERTABLE_USER_PID INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE AUTH
(
	AUTH_PID number NOT NULL,
	AUTH_LEVEL nvarchar2(20) NOT NULL,
	PRIMARY KEY (AUTH_PID)
);


CREATE TABLE INTERS
(
	INTERS_PID number NOT NULL,
	INTERS_INTER nvarchar2(20) NOT NULL,
	INTERS_FK_USER number NOT NULL,
	PRIMARY KEY (INTERS_PID)
);


CREATE TABLE MAINBOARD
(
	MAINBOARD_PID number NOT NULL,
	MAINBOARD_CONTENT nvarchar2(50) NOT NULL,
	MAINBOARD_CREATEAT date DEFAULT SYSDATE,
	MAINBOARD_FK_USER number NOT NULL,
	PRIMARY KEY (MAINBOARD_PID)
);


CREATE TABLE MAINBOARD_COMMENT
(
	MAINBOARD_COMMENT_PID number NOT NULL,
	MAINBOARD_COMMENT_CONTENT nvarchar2(20) NOT NULL,
	MAINBOARD_COMMENT_CREATEAT date DEFAULT SYSDATE,
	MAINBOARD_COMMENT_FK_MAINBOARD number NOT NULL,
	MAINBOARD_COMMENT_FK_USER number NOT NULL,
	PRIMARY KEY (MAINBOARD_COMMENT_PID)
);


CREATE TABLE MAINBOARD_COMMENT_COMMENT
(
	MAINBOARD_COMMENT_COMMENT_PID number NOT NULL,
	MAINBOARD_COMMENT_COMMENT_CONTENT nvarchar2(20) NOT NULL,
	MAINBOARD_COMMENT_COMMENT_CREATEAT date DEFAULT SYSDATE,
	MAINBOARD_COMMENT_COMMENT_FK_COMMENT number NOT NULL,
	MAINBOARD_COMMENT_COMMENT_FK_USER number NOT NULL,
	PRIMARY KEY (MAINBOARD_COMMENT_COMMENT_PID)
);


CREATE TABLE MAINBOARD_COMMENT_LIKE
(
	MAINBOARD_COMMENT_LIKE_PID number NOT NULL,
	MAINBOARD_COMMENT_LIKE_FK_COMMENT number NOT NULL,
	MAINBOARD_COMMENT_LIKE_FK_USER number NOT NULL,
	PRIMARY KEY (MAINBOARD_COMMENT_LIKE_PID)
);


CREATE TABLE MAINBOARD_LIKE
(
	MAINBOARD_LIKE_PID number NOT NULL,
	MAINBOARD_LIKE_FK_MAINBOARD number NOT NULL,
	MAINBOARD_LIKE_FK_USER number NOT NULL,
	PRIMARY KEY (MAINBOARD_LIKE_PID)
);


CREATE TABLE MAINBOARD_MEDIA
(
	MAINBOARD_MEDIA_PID number NOT NULL,
	MAINBOARD_MEDIA_URI nvarchar2(50) NOT NULL,
	MAINBOARD_MEDIA_TYPE nvarchar2(20) NOT NULL,
	MAINBOARD_MEDIA_FK_MAINBOARD number NOT NULL,
	PRIMARY KEY (MAINBOARD_MEDIA_PID)
);


CREATE TABLE MAINBOARD_TAG
(
	MAINBOARD_TAG_PID number NOT NULL,
	MAINBOARD_TAG_TAGNAME nvarchar2(20) NOT NULL,
	MAINBOARD_TAG_FK_MAINBOARD number NOT NULL,
	PRIMARY KEY (MAINBOARD_TAG_PID)
);


CREATE TABLE RELATION
(
	RELATION_PID number NOT NULL,
	RELATION_CREATEAT date DEFAULT SYSDATE,
	RELATION_FK_SUPPORTER_ID number NOT NULL,
	RELATION_FK_DEPENDENT_ID number NOT NULL,
	PRIMARY KEY (RELATION_PID)
);


CREATE TABLE SCHEDULE
(
	SCHEDULE_PID number NOT NULL,
	SCHEDULE_CONTENT nvarchar2(20) NOT NULL,
	SCHEDULE_STARTDATE date DEFAULT SYSDATE,
	SCHEDULE_ENDDATE date DEFAULT SYSDATE,
	SCHEDULE_COLOR nvarchar2(10),
	SCHEDULE_CREATEAT date DEFAULT SYSDATE,
	SCHEDULE_FK_REGIST_USER number NOT NULL,
	SCHEDULE_FK_STATUS number NOT NULL,
	SCHEDULE_FK_TARGET_USER number NOT NULL,
	SCHEDULE_TITLE nvarchar2(20) NOT NULL,
	PRIMARY KEY (SCHEDULE_PID)
);


CREATE TABLE SCHEDULE_ALERT
(
	SCHEDULE_ALERT_PID number NOT NULL,
	SCHEDULE_ALERT_ALERTTIME date DEFAULT SYSDATE,
	SCHEDULE_ALERT_FK_SCHEDULE number NOT NULL,
	PRIMARY KEY (SCHEDULE_ALERT_PID)
);


CREATE TABLE SCHEDULE_MAP
(
	SCHEDULE_MAP_PID number NOT NULL,
	SCHEDULE_MAP_WIDO nvarchar2(20) NOT NULL,
	SCHEDULE_MAP_GYEONGDO nvarchar2(20) NOT NULL,
	SCHEDULE_MAP_FK_SCHEDULE number NOT NULL,
	SCHEDULE_MAP_ADDRESS nvarchar2(20),
	PRIMARY KEY (SCHEDULE_MAP_PID)
);


CREATE TABLE SCHEDULE_MEDIA
(
	SCHEDULE_MEDIA_PID number NOT NULL,
	SCHEDULE_MEDIA_URL nvarchar2(20) NOT NULL,
	SCHEDULE_MEDIA_FK_SCHEDULE number NOT NULL,
	PRIMARY KEY (SCHEDULE_MEDIA_PID)
);


CREATE TABLE SCHEDULE_PUSH
(
	SCHEDULE_PUSH_PID number NOT NULL,
	SCHEDULE_PUSH_FK_SCHEDULE number NOT NULL,
	PRIMARY KEY (SCHEDULE_PUSH_PID)
);


CREATE TABLE SCHEDULE_STATUS
(
	SCHEDULE_STATUS_PID number NOT NULL,
	SCHEDULE_STATUS_CONTENT nvarchar2(20) NOT NULL,
	PRIMARY KEY (SCHEDULE_STATUS_PID)
);


CREATE TABLE USERTABLE
(
	USER_PID number NOT NULL,
	USER_UID nvarchar2(20) NOT NULL,
	USER_PW nvarchar2(20) NOT NULL,
	USER_CALL number NOT NULL,
	USER_EMAIL nvarchar2(30) NOT NULL,
	USER_BIRTH number NOT NULL,
	USER_AUTHCODE number NOT NULL,
	PRIMARY KEY (USER_PID)
);



/* Create Foreign Keys */

ALTER TABLE USERTABLE
	ADD FOREIGN KEY (USER_AUTHCODE)
	REFERENCES AUTH (AUTH_PID)
;


ALTER TABLE MAINBOARD_COMMENT
	ADD FOREIGN KEY (MAINBOARD_COMMENT_FK_MAINBOARD)
	REFERENCES MAINBOARD (MAINBOARD_PID)
;


ALTER TABLE MAINBOARD_LIKE
	ADD FOREIGN KEY (MAINBOARD_LIKE_FK_MAINBOARD)
	REFERENCES MAINBOARD (MAINBOARD_PID)
;


ALTER TABLE MAINBOARD_MEDIA
	ADD FOREIGN KEY (MAINBOARD_MEDIA_FK_MAINBOARD)
	REFERENCES MAINBOARD (MAINBOARD_PID)
;


ALTER TABLE MAINBOARD_TAG
	ADD FOREIGN KEY (MAINBOARD_TAG_FK_MAINBOARD)
	REFERENCES MAINBOARD (MAINBOARD_PID)
;


ALTER TABLE MAINBOARD_COMMENT_COMMENT
	ADD FOREIGN KEY (MAINBOARD_COMMENT_COMMENT_FK_COMMENT)
	REFERENCES MAINBOARD_COMMENT (MAINBOARD_COMMENT_PID)
;


ALTER TABLE MAINBOARD_COMMENT_LIKE
	ADD FOREIGN KEY (MAINBOARD_COMMENT_LIKE_FK_COMMENT)
	REFERENCES MAINBOARD_COMMENT (MAINBOARD_COMMENT_PID)
;


ALTER TABLE SCHEDULE_ALERT
	ADD FOREIGN KEY (SCHEDULE_ALERT_FK_SCHEDULE)
	REFERENCES SCHEDULE (SCHEDULE_PID)
;


ALTER TABLE SCHEDULE_MAP
	ADD FOREIGN KEY (SCHEDULE_MAP_FK_SCHEDULE)
	REFERENCES SCHEDULE (SCHEDULE_PID)
;


ALTER TABLE SCHEDULE_MEDIA
	ADD FOREIGN KEY (SCHEDULE_MEDIA_FK_SCHEDULE)
	REFERENCES SCHEDULE (SCHEDULE_PID)
;


ALTER TABLE SCHEDULE_PUSH
	ADD FOREIGN KEY (SCHEDULE_PUSH_FK_SCHEDULE)
	REFERENCES SCHEDULE (SCHEDULE_PID)
;


ALTER TABLE SCHEDULE
	ADD FOREIGN KEY (SCHEDULE_FK_STATUS)
	REFERENCES SCHEDULE_STATUS (SCHEDULE_STATUS_PID)
;


ALTER TABLE INTERS
	ADD FOREIGN KEY (INTERS_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE MAINBOARD
	ADD FOREIGN KEY (MAINBOARD_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE MAINBOARD_COMMENT
	ADD FOREIGN KEY (MAINBOARD_COMMENT_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE MAINBOARD_COMMENT_COMMENT
	ADD FOREIGN KEY (MAINBOARD_COMMENT_COMMENT_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE MAINBOARD_COMMENT_LIKE
	ADD FOREIGN KEY (MAINBOARD_COMMENT_LIKE_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE MAINBOARD_LIKE
	ADD FOREIGN KEY (MAINBOARD_LIKE_FK_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE RELATION
	ADD FOREIGN KEY (RELATION_FK_SUPPORTER_ID)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE RELATION
	ADD FOREIGN KEY (RELATION_FK_DEPENDENT_ID)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE SCHEDULE
	ADD FOREIGN KEY (SCHEDULE_FK_REGIST_USER)
	REFERENCES USERTABLE (USER_PID)
;


ALTER TABLE SCHEDULE
	ADD FOREIGN KEY (SCHEDULE_FK_TARGET_USER)
	REFERENCES USERTABLE (USER_PID)
;



